spring:
  datasource:
    url: jdbc:h2:mem:credit-application-db
    username: admin
  h2:
    console:
      enabled: true
      path: /h2-console
      setting:
        trace: false
        web-allow-others: false
